### ISSUE TITLE
Reducing Repeated Patterns & Photo Realistic Doodles

### ISSUE THREAD

**Issue by bmaltais** [alexjc/neural-doodle#65]
Check out this test. Pretty interesting:

https://twitter.com/netputing/status/713879168866512900

A bit too many repetitive patterns. I wish there was an option to prevent pattern repetition at the cost of lower quality... but this is an interesting avenue to create photo from doodles. Right now I feel like a bad photoshop but there was actually no photoshop skills involved (except to create the mask for the original picture).

**Comment by bmaltais** [comment]
Better version https://twitter.com/netputing/status/713900409379631106?s=09

**Comment by alexjc** [comment]
Amazing results!!

For repeated patterns, I agree and I have an idea how to address it.  Also, adding some rendering quality improvements like jittering could make a big difference. (I will also try to make time to experiment.)

Otherwise, a few tips for photo-quality render at a higher resolution and downscale. Once my memory optimizations are in this should be easier. You can use CPU for final pass in the meantime until GPU optimizations are in.

**Comment by bmaltais** [comment]
Here is a version based on hand-drawing. Turned out pretty good: https://twitter.com/netputing/status/714105837770264576

Looking forward to future version with duplicate removal and jittering.

**Comment by alexjc** [comment]
The `--variety` parameter can now reduce repeated patterns. Typically set this between `0.0` and `1.0`.
