### ISSUE TITLE
Getting 'NoneType' error

### ISSUE THREAD

**Issue by goldenice** [alexjc/neural-doodle#7]
On my MBP 15" 2015, with El Capitan, I'm getting this error when trying to convert an image:

```
Traceback (most recent call last):
  File "doodle.py", line 449, in <module>
    generator = NeuralGenerator()
  File "doodle.py", line 200, in __init__
    self.content_map_original = np.zeros(self.content_img_original.shape[:2]+(1,))
AttributeError: 'NoneType' object has no attribute 'shape'
```

The command was:
```
python3 doodle.py --style samples/Monet.jpg --output output.png --device=cpu --iterations=1 --save-every 1
```

I'm not that fluent in Python, but am I correct in seeing that a file fails to load or something like that? How should I fix this?

**Comment by alexjc** [comment]
The problem is you're trying to create output without any "doodle" for it. You need to create a file called `output_sem.png` which is your target for the optimization algorithm.

I presume it works with `samples/Coastline.jpg` because it loads `samples/Coastline_sem.png`?

I'll add a better error message ;-)

**Comment by goldenice** [comment]
Ah, right. It was not clear to me the program requires both input and output _sem.png's, so to speak. Thanks for the explanation :)

**Comment by alexjc** [comment]
It should work with these cases:
Two images, minimum source style and target content.
Three images: style+annotation and target annotation.

Better errors is [68c16a2].
